### PR TITLE
Add new method to stop watching data on every animation frame tick

### PR DESCRIPTION
**Pull request by pyxarez**

### CODE REVIEW

**Comment by CrazySquirrel** [comment]
@pyxarez Why not use the .destroy() method?

**Comment by pyxarez** [comment]
Because after using of the destroy method we lose possibility of retrieving data from EverCookie
Due to the wipe of [stores](https://github.com/CrazySquirrel/EverCookie/blob/master/lib/EverCookie.ts#L583)

**Comment by CrazySquirrel** [comment]
@pyxarez Oh, I see. Could you add some additional changes then, please? I think it would be better if you create startWatching method (or just call it start and stop) and change destroy and constructor methods so that they use new stop and start methods.

**Comment by pyxarez** [comment]
Sure
I also wanna know is that good idea to automatically start watcher on initialisation?
Whether class should get additional argument that tells it to start watching?
Something like
```javascript 
constructor(hash?: string, watch?: boolean) {
    ...
    if (watch && this.isSupported()) {
      this.refreshID = this.start();
    }
}

```

**Comment by CrazySquirrel** [comment]
@pyxarez 
It starts watching when creating, because it's necessary to maintain data integrity and protect data from outside changing. There are no additional parameters for observer, it just runs in a serial mode. You can read more about watcher her https://github.com/CrazySquirrel/AnimationFrame
It also start watching when creating, since the main purpose of this class is to save data at any cost.

**Comment by pyxarez** [comment]
@CrazySquirrel okay, is that enough to do a new release?

**Comment by CrazySquirrel** [comment]
@pyxarez You forgot to change the README.md file, but that's okay. I'll change it and create new releases tonight.

**Comment by pyxarez** [comment]
@CrazySquirrel yea, you're right! Thank you for fast response

**Pull request merged**
